### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by kg-kartik** [kg-kartik/CryptX#2]
The documentation doesn't provide much detail about the project and there is not enough information.
Documentation must cover topics :

- Project Description
- Technologies used
- Getting Started: Local installation guide
- Contributing guide

**Comment by prabhu4444** [comment]
Hi, I'd like to contribute to this issue!

**Comment by kg-kartik** [comment]
> Hi, I'd like to contribute to this issue!

Yea sure, I guess you would have more of got what needs to added in documentation.
So I am assigning you the issue, feel free to raise a PR and ping me in case of any doubt!

**Comment by harshalkaigaonkar** [comment]
hi @kg-kartik , i would like to contribute to it.

**Comment by kg-kartik** [comment]
> hi @kg-kartik , i would like to contribute to it.

Yes sure, you can raise PR for the same
